# Generated by Django 6.0.4 on 2026-04-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrecord',
            name='course',
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='department',
            field=models.CharField(choices=[('DICS', 'DICS'), ('BSBA', 'BSBA'), ('BEED', 'BEED')], default='DICS', max_length=10),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='semester',
            field=models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester')], default='1st Semester', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='year_level',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], default='1st Year', max_length=20),
        ),
    ]
